### PR TITLE
Fix bug in Data.isdone and Data.getfield

### PR DESCRIPTION
**Pull request by davidanthoff**
Both of these were triggered when I use [Query.jl](https://github.com/davidanthoff/Query.jl) with a feather source. Would be great if you could merge this and then tag a new release.

### CODE REVIEW

**Comment by quinnj** [comment]
Sorry for the weird state, I'm actually shuffling things around in DataStreams, but haven't pushed some updates. I'm waiting on a few CategoricalArray fixes and then I'll push everything and re-tag.

**Comment by davidanthoff** [comment]
Sure, sounds good!

**Comment by davidanthoff** [comment]
@quinnj I just saw that you fixed one of the bugs in this original PR on master already. So now this PR only has a fix for the other, remaining, error. I think this right now is the only bug that is preventing Query.jl from working with a feather data source.

**Comment by quinnj** [comment]
hey @davidanthoff, sorry for the delay here. I started looking into it and it turns out I had several `Data.isdone` definitions that weren't quite right across the datastream ecosystem. I've corrected them all locally (including Feather.jl), and I'm going to do a few more rounds of testing between the various packages to ensure everything is ship-shape. I'll try and get a new tag out for all the packages sometime next week.

**Comment by davidanthoff** [comment]
Ok, cool. I just tested Feather master with [Query](https://github.com/davidanthoff/Query.jl), and it all seems to work now! As soon as you have tagged a new version, I'll add tests to [Query](https://github.com/davidanthoff/Query.jl) for this scenario.

**Pull request closed without merging**
