### PR TITLE
fix travis badge in readme

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by quinnj** [comment]
Thanks!

**Comment by tkelman** [comment]
Wasn't needed here, but is Travis not enabled for PR's or did something fishy happen?

**Comment by quinnj** [comment]
How do we enable it for PRs? I thought it did that automatically when you turned on Travis. @dmbates may have to tweak something

**Comment by tkelman** [comment]
It should, but repo moves can confuse it sometimes? Any JuliaStats admin should be able to check under the github settings and/or the travis settings.

**Comment by quinnj** [comment]
I see the switch turned on at https://travis-ci.org/JuliaStats/Feather.jl/settings

**Comment by tkelman** [comment]
It's possible this was just merged too quickly for the webhook to catch up... keep an eye out, anyway.

**Comment by quinnj** [comment]
good to know

**Pull request merged**
