### PR TITLE
Fix streamtype error on 0.4

### PR DESCRIPTION
**Pull request by ararslan**
and a couple of other things

### CODE REVIEW

**Comment by ararslan** [comment]
Not sure what the precompilation issue on 0.5 is about, but it looks like the 0.4 failure regarding `streamtype` is because it was added to DataStreams since the last release and there hasn't yet been a release that includes it. @quinnj Could you tag a new DataStreams version if it's ready for another release?

**Comment by quinnj** [comment]
precompiling was due to a bug in how enums are runtime-dependent on hashing. I think it was fixed on master, but I haven't had a chance to verify. 

DataStreams is almost ready for a new release. I have a few more things to clean up in ODBC and then I'll push new tags all around.

**Comment by ararslan** [comment]
Looks like this PR is unnecessary now?

**Comment by ararslan** [comment]
We should still precompile though, if nothing else.

**Comment by quinnj** [comment]
We should still precompile, I need to see if that will work on 0.4 though.

**Pull request closed without merging**
