### PR TITLE
Add badges and enable Coveralls

### PR DESCRIPTION
**Pull request by ararslan**
I also changed `release` to `0.4` in the Travis YAML since 0.5 will soon be the new release.

### CODE REVIEW

**Comment by ararslan** [comment]
My organization member privileges are weird for some of the JuliaStats repos. For example, I don't have write access here. No idea why.

**Comment by quinnj** [comment]
+1. Thanks.

**Comment by ararslan** [comment]
Hey @quinnj, since you're a JuliaStats owner can you fix the permissions on Feather and Rmath? It looks like non-owner members don't have write access, maybe because these were (I think?) transferred to JuliaStats from other places.

**Comment by quinnj** [comment]
Ok, should be fixed.

**Comment by ararslan** [comment]
Awesome, thanks! You rock! 🎸 :metal: 👏

**Pull request merged**
